service: gniapp-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  environment:
    MONGO_URI: ${env:MONGO_URI}
  httpApi:
    cors:
      allowedOrigins:
        - https://www.gniapp.com
        - https://demo-gni.gofastapi.com
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization

functions:
  app:
    handler: lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'

# plugins:
#   - serverless-offline

package:
  exclude:
    - node_modules/aws-sdk/**
